
export const REFRESH_TOKEN_STATUS = {
    STANDARD: '',
    LOADING: 'REFRESH_LOADING',
    ERROR: 'REFRESH_ERROR',
    SUCCESS: 'SUCCESS',
  };
  
export const REFRESH_TOKEN_ACTIONS = {
    STANDARD: '',
    PENDING: 'REFRESH_PENDING',
    FULFILLED: 'REFRESH_FULFILLED',
    REJECTED: 'REFRESH_REJECTED',
};
