export const AUTH_STATUS = {
    STANDARD: '',
    LOADING: 'AUTH_LOADING',
    ERROR: 'AUTH_ERROR',
    SUCCESS: 'AUTH_SUCCESS',
  };
  
  export const AUTH_ACTIONS = {
    STANDARD: '',
    PENDING: 'LOGIN_PENDING',
    FULFILLED: 'LOGIN_FULFILLED',
    REJECTED: 'LOGIN_REJECTED',
  };
  