export const RENTALS_STATUS = {
    STANDARD: '',
    LOADING: 'RENTAL_LOADING',
    ERROR: 'RENTAL_ERROR',
    SUCCESS: 'RENTAL_SUCCESS',
}

export const RENTALS_ACTIONS = {
    STANDARD: '',
    PENDING: 'RENTAL_PENDING',
    FULFILLED: 'RENTAL_FULFILLED',
    REJECTED: 'RENTAL_REJECTED',
}
